### PR TITLE
WIP: Add image paste functionality

### PR DESCRIPTION
**Pull request by ljrk0**
Hi, this implements #74, however I'm neither a Python person, nor a GUI/GTK person, so this is highly hacky.  Maybe this can be a basis for proper implementation?

### CODE REVIEW

**Comment by amka** [comment]
Haha! I started working on the same feature a few days ago, thank you for submitting the PR, I will review it.

**Comment by ljrk0** [comment]
Awesome!  I'm happy to also help with refactoring (Currently I call into the screenshot service for decoding) and applying any other fixes, also of course the code smell detected by the CI.  I hope I can get to that tomorrow, any feedback appreciated!

**Comment by amka** [comment]
@ljrk0 I'll close this due to implemented in a main branch with your help 🤗  Thank you!

**Comment by ljrk0** [comment]
Awesome, I love your improvements to my initial draft, thank you! :3

**Pull request closed without merging**
